package com.cryptotelegram.states;

public enum BotState{
    FREESTATE,
    SETPRICEFORALERT,
    GETCOININFO,
    ADDNEWCOIN,
    DELETECOIN,
    SETPERCENTAGEFORALERT,
    WAITINGSETPERCENTAGEFORALERT,
    WAITINGDELETEPRICEFORALERT,
    WAITINGSETPRICEFORALERT,
    DELETEPERCENTAGEFORALERT,
    DELETEPRICEFORALERT

}
